### ISSUE TITLE
[Meta] OgRole tear down initiative

### ISSUE THREAD

**Issue by RoySegall** [amitaibu/og#107]
What we need to do:
- [ ] Validation handle - verify we can't assign a role to a non existing group, verify the permission exists before assign it to the role, verify the entity type and entity bundle exists and defined as group(#106).
- [x] Add field to allow overriding roles and permission.
- [ ] Make sure that each group can override a role and permissions.
- [ ] Alter the general query object for when searching a role in group which overrides the roles and permissions. Since the ID of a overridden role is different, the query should know how to handle it.
- [ ] Do a research on how to connect the user and to the group roles - should we have a content entity? should we have a field on the user? should we do this at the membership level(this is a little bit extreme)?
- [ ] Plug `OgRole` to [OgAccess:UserAccess](https://github.com/amitaibu/og/blob/8.x-1.x/src/OgAccess.php#L64)
- [ ] Plug `OgRole` to [OgAccess:UserEntityAccess](https://github.com/amitaibu/og/blob/8.x-1.x/src/OgAccess.php#L159)

**Comment by chx** [comment]
So where are we with this and how can I help.

**Comment by amitaibu** [comment]
Now the #128 is in, it means that OgMembership entity will be created only when relating `User` to group. Otherwise it will be a normal entity reference field, with no OgMembership created.

This means, we can now add a (multiple) reference field to OgMemebership that will reference OgRole(s) - and model it closer to how D8's site wide users are related to site wide roles.

**Comment by chx** [comment]
Can we chat about how can I help this? :)

**Comment by amitaibu** [comment]
Sure, I'll be online in ~20

**Comment by amitaibu** [comment]
Going to login, seems I don't even have IRC client on my work computer  :)

**Comment by damiankloip** [comment]
Shame! :bell: :bell: Shame! :)
